# Setup
title:               í•œê±¸ìŒì”© ì²œì²œíˆ
tagline:             'The growing develope'
url:                 http://siyul-park.github.io
description:         'become a developer who has a positive influence to others ğŸ”­'
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Ara Park
  url:               https://www.linkedin.com/in/siyul-park
  email:             siyual.bak@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
